### ISSUE TITLE
Some errors when using expand_query function

### ISSUE THREAD

**Issue by kzhong130** [haochenuw/SealPIR#1]
Hi, I have added example codes and descriptions to this repo (https://github.com/kzhong130/seal-expand-example). Please take a look at that, thank you very much for helping out with this! Let me know if there is anything unclear.

**Comment by haochenuw** [comment]
There appears to be some strange memory corruption issue with the code. After I refactored the expand_query function it seems to magically work for 3.5.6. Will push the code soon and you can test it out.

**Comment by haochenuw** [comment]
Okay, I made a pull request to your repo, which fixes the issue (at least on my machine). It's actually a bit tricky to update SealPIR to SEAL3.5.x, since the decomposition bit count option for generating galois keys is removed. For now it might be best to keep using the older version of SEAL.
